
language: lisp

env:
  matrix:
    # - LISP=abcl
    - LISP=sbcl
    # - LISP=sbcl32
    # - LISP=ccl
    # - LISP=ccl32
    # - LISP=clisp
    # - LISP=clisp32
    # - LISP=cmucl
    # - LISP=ecl

install:
 - curl https://raw2.github.com/luismbo/cl-travis/master/install.sh | bash

script:
 - cl-launch -i "(ql:quickload :cl-plus-test) (uiop:quit (if (cl+t:run-tests) 0 1))"

notifications:
  email:
    - tkych.repl+travis-ci@gmail.com